#!/bin/sh

getmem() {
	awk '
	/^MemTotal:/ { total = $2; }
	/^MemAvailable:/ { available = $2; }

	END {
		printf "%d MB / %d MB\n", (available / 1024), (total / 1024);
	}
	' < /proc/meminfo
}

while true;
do
	getmem
	sleep 1
done
