#!/bin/sh

getmem() {
	awk '
	/^MemTotal:/ { total = $2; }
	/^MemAvailable:/ { available = $2; }

	END {
		printf "%8.2f MB / %8.2f MB\n", (available / 1024.0), (total / 1024.0);
	}
	' < /proc/meminfo
}

while true;
do
	getmem
	sleep 1
done
